### ISSUE TITLE
call_throttled() can't return values.

### ISSUE THREAD

**Issue by cadennabors** [ImmersiveRPG/ExampleGodotThrottle#1]
call_throttled() can't return values, which hinders it's usage.

I am attempting to use this for a physics check in a heavy function, and that can obviously get ahead of the target time
ex:
`	while counter >= 0 and collision_exceeds_threshold == false:
		var volume = AABBCollision(RoomList[RoomList.size() - 1], RoomList[counter])`
this would not work with

`	while counter >= 0 and collision_exceeds_threshold == false:
		var volume = CallThrottled.call_throttled(AABBCollision, RoomList[RoomList.size() - 1], RoomList[counter])`

This is a great addon, but it could be greater with return values.

**Comment by workhorsy** [comment]
Thanks for the input. But I want to keep call_throttled as an alternative to call_deferred. So there isn't a direct way to return something from a function like that. This easiest way to get around that, is to use a custom signal to emit the data, instead of returning it. Then you can call emit every time you want to "return" something.

I hope this helps.

https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#custom-signals

**Comment by workhorsy** [comment]
I'm closing this for now. Let me know if you have any other issues. Thanks
